#define FFCONF_DEF 86606
#define FF_FS_READONLY 0
#define FF_FS_MINIMIZE 0
#define FF_USE_LABEL 0
#define FF_CODE_PAGE 932 //932
#define FF_USE_LFN 0
#define FF_FS_RPATH 0
#define FF_VOLUMES 1
#define FF_MULTI_PARTITION 0
#define FF_MAX_SS 512
#define FF_FS_EXFAT 0
#define FF_NORTC_MON 1
#define FF_NORTC_MDAY 1
#define FF_NORTC_YEAR 2019